### ISSUE TITLE
Error in distance_to using topology(roadNetwork)

### ISSUE THREAD

**Issue by NaroaCS** [NaroaCS/MultifunctionalVehicles#1]
Hi @agrignard,

I have been facing a strange behavior when using the function `distance_to using topology(roadNetwork)`. (See code [here](https://github.com/NaroaCS/MultifunctionalVehicles/blob/e36d68a5e3240894e87de14c9a8d23bb3b5d1c64/models/Agents.gaml#L9) ) If I use the regular `distance_to`, the distances are in the order of 20-1000m, which seems quite right. But if I use the roadNetwork topology it gives distances in the orders of 20,000m and it doesn't make any sense (we are using Cambridge as a scenario, and we have 200 bikes). For the rest, the roadNetwork is working well, so I don't think the roadNetwork is the problem.
This started to happen only with the last GAMA update that I did, but it used to work before. I don't know what was the previous version (sorry) but now I'm using _GAMA_1.8.2_Windows_with_JDK_01.25.22_081b1605_. 

Any ideas of why this might be happening? I'd greatly appreciate any help :)

**Comment by agrignard** [comment]
This is typically a question that can be raised on Gama Github (as it seems that this is something related to GAMA itself and maybe the version you are using (so can be interesting for GAMA to know on which version it works and on which it doesn't)

https://github.com/gama-platform/gama/issues

**Comment by NaroaCS** [comment]
Will do! Thanks for helping always @agrignard ! :)
